set(HQ_COMMON_TEST_ROOT "${CMAKE_CURRENT_LIST_DIR}")
set(HQ_COMMON_TEST_RUNNER "${HQ_COMMON_TEST_ROOT}/tests.c")

if(DEFINED CMAKE_SCRIPT_MODE_FILE)
  file(GLOB HQ_COMMON_OSAL_TEST_SOURCES
    "${HQ_COMMON_TEST_ROOT}/osal/*.c"
  )
else()
  file(GLOB HQ_COMMON_OSAL_TEST_SOURCES CONFIGURE_DEPENDS
    "${HQ_COMMON_TEST_ROOT}/osal/*.c"
  )
endif()

list(SORT HQ_COMMON_OSAL_TEST_SOURCES)